import type { Metadata } from "next";
import { Montserrat } from "next/font/google";
import "./globals.css";
import Header from "./components/Header";
import Footer from "./components/Footer";
import Headermobile from "./components/Headermobile";

const montserrat = Montserrat({
  subsets: ["latin"], // "Latin" debe ser minúscula
  weight: ["300", "400", "500", "600", "700", "800", "900"], // Los pesos deben ser strings
  variable: "--font-montserrat",
})

export const metadata: Metadata = {
  title: "Automotores Yrigoyen",
  description: "Generated by create next app",
  icons:{
    icon:"/favicon.ico"
  }
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html className={`${montserrat.variable}`} lang="es">
      <head>
      <link rel="icon" href="/favicon.ico" sizes="any" />
      </head>
      <body
        className={`${montserrat.className}antialiased bg-[#fdf7f7]`}
      >
        <Header />
        <Headermobile />
        {children}
        <Footer />
      </body>
    </html>
  );
}
