import FormFinancing from "../components/contact/FormFinancing";
import { Metadata } from "next";

export const metadata: Metadata = {
  title: "Automotores Yrigoyen | Cars",
  description: "Generated by create next app",

};

export default function FinancingPage() {
  return (
    <section className="pt-18 w-full">
      <FormFinancing />
    </section>
  )
}
